# Configuration

# freya.io

core:
  git: https://github.com/xyncro/freya
  twitter: https://twitter.com/freyafs
  # url: http://localhost:4000
  url: https://freya.io

# docs.freya.io
  
docs:
  git: https://github.com/xyncro/sites-freya.io
  # url: http://localhost:8000
  url: https://docs.freya.io/en/latest

# Build

markdown: kramdown

# Exclusions

exclude: [

  # Common

  LICENSE.md,
  README.md,

  # Jekyll
  
  Gemfile,
  Gemfile.lock,

  # Sphinx

  _build,

  conf.py,
  Makefile,

  index.rst,
  meta,
  recipes,
  reference,
  topics,
  tutorials

]
